### ISSUE TITLE
IMAP MailBox Editor Folder configuration - folder not selectable

### ISSUE THREAD

**Issue by mariodavid** [cuba-platform/imap-addon#2]
Hi,

when selecting a IMAP folder via the configuration UI (Select folders), the selection does not get taken over on the editor table. Therefore the user is not able to configure Folder Events since it is not possible to select the entry in the folder table.

I showed and explained the UI bug here: https://youtu.be/AoPj2azW6O8

**Comment by shmelev-haulmont** [comment]
Hello Mario,

Thank you for detailed description of the issue. The screen for IMAP Mailbox was completely redesigned for folders configuration, there is no more "Select folders" button. Please take a look at last changes. Will appreciate your feedback.

Thanks,
Maksim
