### ISSUE TITLE
IMAP MailBox Configuration Edit - possible to create Event without selecting a Folder

### ISSUE THREAD

**Issue by mariodavid** [cuba-platform/imap-addon#3]
Currently it is possible to create a Folder event without having selected the corresponding Folder before.

I assume the Event creation should only be allowed after there has been a Folder selected - correct?

<img width="855" alt="folder-events-table-disabled" src="https://user-images.githubusercontent.com/817400/38043725-36e45c22-32b8-11e8-835b-ba708abcd49c.png">

**Comment by shmelev-haulmont** [comment]
Mario,

Please see https://github.com/cuba-platform/imap-addon/issues/2

Thanks,
Maksim
