### ISSUE TITLE
Change field with button to PickerField

### ISSUE THREAD

**Issue by smianna** [cuba-platform/imap-addon#31]
**Steps to reproduce:**
1. Open Menu: Administration → IMAP → IMAP Configuration.
2. Click *Create*.
3. Tick the *Use trash folder for removal* checkbox in the *Advanced* section.

The *Name of folder to use the trash bin* field is implemented as a combination of a button and a simple field (see the attached figure below). Instead of this, the Simple PickerField component should be used (for more details, please refer to [CUBA Sampler](https://demo.cuba-platform.com/sampler/#!)).

![default](https://user-images.githubusercontent.com/38000666/39706703-4974bde8-5223-11e8-887d-2aa6af0c3c26.png)

**Comment by shmelev-haulmont** [comment]
fixed
