### ISSUE TITLE
[IMAP Configuration Editor] Scroller works improperly

### ISSUE THREAD

**Issue by smianna** [cuba-platform/imap-addon#33]
**Preconditions:**
* An IMAP configuration should be created.

**Steps to reproduce:**
1. Open Menu: Administration → IMAP → IMAP Configuration.
2. Select the configuration and click *Edit*.
3. Wait for the folder table to download.
4. Try expanding several parent folders.

**ER:** There should be an ability to scroll the table. For example, if there are many parent folders, it is easier to navigate if scrolling is available.

**AR:** At first, a scroller does not appear at all, then it appears for the whole screen, and after that, for the table. See this [GIF](http://g.recordit.co/olpKi3vwn1.gif).

**Comment by smianna** [comment]
I can still reproduce the issue

**Comment by shmelev-haulmont** [comment]
fixed
