### ISSUE TITLE
[Email Viewer][Cosmetics] Size of attachments table should be fixed

### ISSUE THREAD

**Issue by smianna** [cuba-platform/imap-addon#41]
**Steps to reproduce:**
1. Open Menu: Administration → IMAP → IMAP Message Browser.
2. *View* an email.
3. Go to the *Attachments* tab.

**ER:** The table displayed on the *Attachments* tab should be of the same size as the first column in the field group (see the figure below).

![default](https://user-images.githubusercontent.com/38000666/39770567-7203174a-5300-11e8-8c79-465cfdd869dd.png)

**AR:** The table size is not fixed at all and changes when changing the size of columns (see this [GIF](http://g.recordit.co/dxF2Wrlb3S.gif)).

**Comment by shmelev-haulmont** [comment]
fixed
