### ISSUE TITLE
Improve localization of attachment titles

### ISSUE THREAD

**Issue by smianna** [cuba-platform/imap-addon#42]
**Preconditions:**
* Create a connection with the *imap.yandex.ru* host.

**Steps to reproduce:**
1. Open Menu: Administration → IMAP → IMAP Message Browser.
2. Open an email that contains an attachment with a title is in Cyrillic.
3. Open the *Attachments* tab.

**Expected Result:** Cyrillic letters are displayed properly.
**Actual Result:**
![image](https://user-images.githubusercontent.com/38000666/39926254-aac482c6-553f-11e8-93c9-f70a537e9156.png)

**Comment by shmelev-haulmont** [comment]
Fixed with upgrading to new version of javax.mail and enabling UTF8=ACCEPT capability, to apply fix for existing attachments you need to delete all attachments of incorrect messages and clear the is_atl column of those messages
