### ISSUE TITLE
@Component EventListener is not found

### ISSUE THREAD

**Issue by mariodavid** [cuba-platform/imap-addon#5]
When i tried to create an EventListener, the first thing that i tried was to create a Spring Bean via @Component. Just like that:

```
@Component("app_myListener")
public class MyListener {

    @EventListener
    public void doIt(NewEmailImapEvent myEvent) {
        //do your stuff
    }
}
```

But in the UI it was not picked up and therefore not selectable. Only when I created a Service with a corresponding Service Interface it worked perfectly.

I think it has to do with the fact, that the Lookup mechanism searches for all methods in the interfaces the bean implements (perhaps this is even CUBA core logic). Perhaps you can just confirm that a Service has to be used. Would be totally ok for me. But if i'm just doing something wrong here, you might point me into the right direction.

Thx

**Comment by shmelev-haulmont** [comment]
Hello Mario,

Fixed in https://github.com/cuba-platform/imap-addon/commit/dd35dd01422431edd0b015b7892c6c2432801891

Thanks,
Maksim
