### ISSUE TITLE
Removed folders do not disappear from table

### ISSUE THREAD

**Issue by smianna** [cuba-platform/imap-addon#60]
**Steps to reproduce:**
1. Open IMAP Configuration Editor.
2. Remove a folder on the email server side.
3. Refresh the table of folders.

**Actual Result:** The removed folder is crossed out (see the figure below).
![image](https://user-images.githubusercontent.com/38000666/41148081-1ec1690c-6b19-11e8-97dc-8505ba7fba58.png)

4. Click *OK* to save the changes.
5. Open the same configuration for editing again.
6. Refresh the table of folders.

**Expected Result:** The folder that was removed from the email server should disappear from the table.
**Actual Result:** The removed folder is still displayed (crossed out).

**Comment by zaharchenko-evgeny** [comment]
Removed folder should be visible and crossed out only in this folder was previously configured in IMAP configuration
