### ISSUE TITLE
Add horizontal scroll to Email Viewer

### ISSUE THREAD

**Issue by smianna** [cuba-platform/imap-addon#61]
It is required to add a horizontal scroll to Email Viewer because some messages cannot be read.
![image](https://user-images.githubusercontent.com/38000666/42770078-2757b8de-8935-11e8-82f0-c029edcacab8.png)

**Comment by smianna** [comment]
After adding a scroll, the fields for displaying email details have shrunk.
![image](https://user-images.githubusercontent.com/38000666/43005149-fdda9f24-8c42-11e8-9bb6-0abb7a2119e7.png)

**Comment by smianna** [comment]
Some text bodies are shrunk as well
![image](https://user-images.githubusercontent.com/38000666/43005479-097f06a2-8c44-11e8-8cca-39a41acd7fdd.png)

**Comment by oshiryaeva** [comment]
Fixed
Possible regression: #66, #67
