### ISSUE TITLE
Font style glitch on email loading

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/imap-addon#66]
Addon version: 0.1-SNAPSHOT
Browsers: Chrome, Firefox, Opera. (didn't try in Safari)

Pre-reqs: active IMAP connection to a mailbox

WTR
1. Administration > IMAP > Imap message browser
1. Select any mail that requires a vertical scroll > View

AR:
While loading, the standard CUBA fonts are displayed.
When the mail is loaded, the font glitch occurs to all text in the app: the captions in `ImapMessageEdit` screen, the tab captions, and the menu captions. 

![imap-fonts](https://user-images.githubusercontent.com/11287637/43202629-07ef436e-902d-11e8-80fc-faf109e9753b.gif)

ER:
Vertical scroll should not affect the page/app style.

**Comment by oshiryaeva** [comment]
regression: default frame height is too small

![imap-scroll-3](https://user-images.githubusercontent.com/11287637/43305371-9d1b6fec-9188-11e8-9021-cede9c1da076.gif)

**Comment by shmelev-haulmont** [comment]
fixed height issue
