### ISSUE TITLE
Double vertical scrollbar in IE11

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/imap-addon#67]
Addon version: 0.1-SNAPSHOT
Browser: IE11 (11.0.9600.19080)

Pre-reqs: active IMAP connection to a mailbox

WTR

1. Administration > IMAP > Imap message browser
2. Select any mail that requires a vertical scroll > View
3. Scroll the mail vertically

AR
Two vertical scrollbars appear on the `ImapMessageEdit` screen: one for mail (useless) and one for the whole page (working).

![imap-scroll-2x](https://user-images.githubusercontent.com/11287637/43203156-70838272-902e-11e8-98a0-a5d96f2fd154.gif)

ER
One scrollbar only

**Comment by oshiryaeva** [comment]
regression: default frame height is too small

![imap-scroll-3](https://user-images.githubusercontent.com/11287637/43305371-9d1b6fec-9188-11e8-9021-cede9c1da076.gif)

**Comment by shmelev-haulmont** [comment]
fixed height issue
