### ISSUE TITLE
Not existing IMAP init config leads to NPE

### ISSUE THREAD

**Issue by mariodavid** [cuba-platform/imap-addon#74]
hi,

i've found a problem that is related to the `app.properties` entries:
```
imap.encryption.key = HBXv3Q70IlmBMiW4EMyPHw==
imap.encryption.iv = DYOKud/GWV5boeGvmR/ttg==
```

If those keys are not defined, there is a NPE in this line:
https://github.com/cuba-platform/imap-addon/blob/master/modules/core/src/com/haulmont/addon/imap/crypto/DefaultEncryptor.java#L44

since `imapConfig.getEncryptionKey()` returns null. Therefore:
```
        public byte[] decode(String src) {
            return decode(src.getBytes(StandardCharsets.ISO_8859_1));
        }
```

is not capable of doing its job.

Should probably be switched to more defensive style like here with the IV:
https://github.com/cuba-platform/imap-addon/blob/master/modules/core/src/com/haulmont/addon/imap/crypto/DefaultEncryptor.java#L48

But I actually would more like to see if it fails with a specific exception, instead of not initializing `iv` as in here: https://github.com/cuba-platform/imap-addon/blob/master/modules/core/src/com/haulmont/addon/imap/crypto/DefaultEncryptor.java#L49
in case the key is missing. 

Even better would be either to not make the values required at all e.g. through adding default values in the config interface: https://github.com/cuba-platform/imap-addon/blob/master/modules/global/src/com/haulmont/addon/imap/config/ImapEncryptionConfig.java

Bye
Mario

**Comment by shmelev-haulmont** [comment]
Hello,

Added check for this property, in case if it's missing an IllegalStateException with message 'Cannot configure encryptor com.haulmont.addon.imap.crypto.DefaultEncryptor, property "imap.encryption.key" is not set' will be raised.
