### ISSUE TITLE
Security issue with Key and IV

### ISSUE THREAD

**Issue by tdltdl** [cuba-platform/imap-addon#90]
### Environment

- Platform version: 7.1.1
- Addon version: 1.3.1 and head

### Description of the bug or enhancement

In DefaultEncryptor, the private key and IV are logged as info which leaks critical information.

```
        log.info("Encryptor has been initialised with key {} and init vector {}",
                imapConfig.getEncryptionKey(), imapConfig.getEncryptionIv()
        );
```
The private key and IV should not be logged.
Also storing the private key should not be stored in a property file. It should be possible to use a key store.

The documentation should maybe explain the purpose of the key and IV (as it looks it is used to decrypt a password for a mailbox if I am correct). Chances are that everybody will tend to use the default key and IV.

**Comment by zaharchenko-evgeny** [comment]
The issue will be fixed in `1.4.1` addon version
