### ISSUE TITLE
Create predefined roles

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/imap-addon#93]
### Environment

- Platform version: 7.2.x
- Addon version: 1.5.x

### Description

Create predefined system roles

**Comment by zaharchenko-evgeny** [comment]
**IMAP Admin role** - allows user to configure IMAP events

**Comment by dmakagonova** [comment]
Platform version: 7.2.3
Addon version: 1.5-SNAPSHOT

1. Run IMAP demo
2. Create a new user (login = user, password = user)
3. Login as user
4. Click Adminstration

Expected result: there is only one menu item IMAP
Actual result: there are all menu items
